name: Seagrampearce
favicon: null
layout_spectrum: 0.3812075317837298
typography_spectrum: 0.10049144714139402
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#242a29'
    - '#c0ada3'
    - '#e4e4e6'
    - '#7a635b'
  brandStrength: 0.16137975524179637
  lightness: 0.38113836850970984
  saturation: 0.32690977677702904
  rhythmicContrast: 0.8905636288691312
purpose: []
